In [1]:
import numpy as np

In [2]:
kernels = np.load('neural_kernels_cifar10.npz')
list(kernels)

['cifar10_train_kernel',
 'cifar10_test_kernel',
 'cifar_10_1_test_kernel',
 'labels_cifar10_train',
 'labels_cifar10_test',
 'labels_cifar10_1_test']

In [5]:
kernels['cifar10_test_kernel'].shape

(10000, 100000)

In [7]:
N = 50000

"""
np.savez('kernels_50k.npz', 
         train_kernel=kernels['cifar10_train_kernel'][:N, :N],
         test_kernel=kernels['cifar10_test_kernel'][:, :N],
         test_1_kernel=kernels['cifar_10_1_test_kernel'][:, :N],
         labels_train=kernels['labels_cifar10_train'][:N],
         labels_test=kernels['labels_cifar10_test'][:N],
         labels_test_1=kernels['labels_cifar10_1_test'][:N])
"""

In [23]:
kernels_50k = np.load('kernels_50k.npz')
list(kernels_50k)

['train_kernel',
 'test_kernel',
 'test_1_kernel',
 'labels_train',
 'labels_test',
 'labels_test_1']

In [24]:
kernels_50k['train_kernel'].shape, kernels_50k['test_kernel'].shape, kernels_50k['test_1_kernel'].shape

((50000, 50000), (10000, 50000), (2000, 50000))

In [25]:
kernels_50k['labels_train'].shape, kernels_50k['labels_test'].shape, kernels_50k['labels_test_1'].shape

((50000,), (10000,), (2000,))

In [17]:
N = 12800
"""
np.savez('kernels_12k.npz', 
         train_kernel=kernels_50k['train_kernel'][:N, :N],
         test_kernel=kernels_50k['test_kernel'][:, :N],
         test_1_kernel=kernels_50k['test_1_kernel'][:, :N],
         labels_train=kernels_50k['labels_train'][:N],
         labels_test=kernels_50k['labels_test'][:N],
         labels_test_1=kernels_50k['labels_test_1'][:N])
"""

In [20]:
kernels_12k = np.load('kernels_12k.npz')
list(kernels_12k)

['train_kernel',
 'test_kernel',
 'test_1_kernel',
 'labels_train',
 'labels_test',
 'labels_test_1']

In [21]:
kernels_12k['train_kernel'].shape, kernels_12k['test_kernel'].shape, kernels_12k['test_1_kernel'].shape

((12800, 12800), (10000, 12800), (2000, 12800))

In [22]:
kernels_12k['labels_train'].shape, kernels_12k['labels_test'].shape, kernels_12k['labels_test_1'].shape

((12800,), (10000,), (2000,))

In [27]:
train_kernel = kernels_12k['train_kernel']
test_kernel  = kernels_12k['test_kernel']

labels_train = kernels_12k['labels_train']
labels_test  = kernels_12k['labels_test']

In [28]:
train_kernel[:5,:5]

array([[1.        , 0.9970431 , 0.99326016, 0.99775115, 0.99663821],
       [0.9970431 , 1.        , 0.99160902, 0.99755973, 0.99511681],
       [0.99326016, 0.99160902, 1.        , 0.99146622, 0.99227528],
       [0.99775115, 0.99755973, 0.99146622, 1.        , 0.99552235],
       [0.99663821, 0.99511681, 0.99227528, 0.99552235, 1.        ]])

In [35]:
test_kernel[:5,:5] * 0.9969 / 1.11196261

array([[0.9969    , 0.99707096, 0.9932627 , 0.99698512, 0.99480632],
       [0.67889957, 0.67897143, 0.67514772, 0.67864657, 0.67992822],
       [0.92934084, 0.92932475, 0.92861989, 0.92821194, 0.92760163],
       [0.84407326, 0.84456551, 0.84315148, 0.84318096, 0.84261198],
       [1.11881171, 1.11868099, 1.11116707, 1.11852208, 1.11591263]])

In [32]:
labels_train[:10]

array([6, 9, 9, 4, 1, 1, 2, 7, 8, 3])

In [31]:
labels_test[:10]

array([3, 8, 8, 0, 6, 6, 1, 6, 3, 1])